[project]
name = "cq"
version = "0.1.0"
description = "A terminal country guesser game"
readme = "README.md"
authors = [
    { name = "aleckshen", email = "aleckshn@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.scripts]
cq = "cq:main"

[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"
